services:
  postgres:
    image: postgres:17.6-alpine
    env_file:
      - docker.dev.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peach -d hotel_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --bind 0.0.0.0 --port 6379
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - docker.dev.env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - docker.dev.env
    ports:
      - "9000:9000"

volumes:
  pgdata:
  redis: