FROM node:22.18.0

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev --no-progress --prefer-offline || npm i --omit=dev

COPY . .

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=5 CMD node -e "require('./database/postgreDB/pg').query('SELECT 1').then(()=>process.exit(0)).catch(()=>process.exit(1))" || exit 1

CMD ["node", "server.js"]

FROM node:22.18.0

WORKDIR /app

COPY package*.json ./

RUN npm install -g nodemon && npm install

COPY . .

EXPOSE 3000

CMD ["nodemon", "server.js"]