CREATE TABLE IF NOT EXISTS handover_daily_settings (
  business_date DATE PRIMARY KEY,
  cash_reserve NUMERIC(10,2) NOT NULL CHECK (cash_reserve >= 0),
  set_by VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
