"use strict";

const tableName = "douyin_orders";

const createQuery = `CREATE TABLE IF NOT EXISTS ${tableName} (
  id BIGSERIAL PRIMARY KEY,
  ota_order_id VARCHAR(64) NOT NULL UNIQUE,
  account_id VARCHAR(64),
  order_status VARCHAR(32),
  guest_name VARCHAR(128),
  guest_mobile VARCHAR(64),
  check_in_date DATE,
  check_out_date DATE,
  room_count INTEGER,
  amount DECIMAL(12, 2),
  currency VARCHAR(16),
  raw_payload JSONB NOT NULL,
  mapped_payload JSONB,
  synced BOOLEAN DEFAULT FALSE,
  system_order_id VARCHAR(64),
  confirm_status VARCHAR(32),
  confirm_number VARCHAR(64),
  confirmed_at TIMESTAMPTZ,
  room_id VARCHAR(64),
  room_name VARCHAR(255),
  source_order_id VARCHAR(64),
  hotel_id VARCHAR(64),
  contact_name VARCHAR(128),
  contact_mobile VARCHAR(128),
  number_of_guests INTEGER,
  amount_before_tax DECIMAL(12, 2),
  rate_plan_id VARCHAR(64),
  biz_type INTEGER,
  remark_from_douyin TEXT,
  remark_from_guest TEXT,
  daily_rates JSONB,
  occupancies JSONB,
  member_info JSONB,
  douyin_log_id VARCHAR(128),
  cancel_id VARCHAR(64),
  cancel_type INTEGER,
  need_audit BOOLEAN,
  after_sale_type INTEGER,
  refund_type INTEGER,
  refund_amount DECIMAL(12, 2),
  user_refund_amount DECIMAL(12, 2),
  penalty_amount DECIMAL(12, 2),
  cancel_reason TEXT,
  cancel_order_time VARCHAR(19),
  refund_order_detail JSONB,
  cancel_status VARCHAR(32),
  cancel_audit_deadline VARCHAR(19),
  cancel_audit_result INTEGER,
  cancel_audit_reason TEXT,
  cancel_audit_status VARCHAR(32),
  cancel_audit_response JSONB,
  cancel_audit_sent_at TIMESTAMPTZ,
  cancel_audit_retry_count INTEGER DEFAULT 0,
  fulfillment_status VARCHAR(32),
  fulfillment_action VARCHAR(32),
  fulfillment_response JSONB,
  fulfillment_sent_at TIMESTAMPTZ,
  refund_status VARCHAR(32),
  refund_result_response JSONB,
  refund_result_received_at TIMESTAMPTZ,
  cancel_finish_time VARCHAR(19),
  confirm_mode INTEGER,
  refund_case_type VARCHAR(32),
  refund_case_status VARCHAR(32),
  suggested_refund_amount DECIMAL(12, 2),
  refund_case_response JSONB,
  booking_stage VARCHAR(32),
  booking_error_code INTEGER,
  booking_error_description TEXT,
  booking_failure_response JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`;

const dropQuery = `DROP TABLE IF EXISTS ${tableName}`;

const createIndexQueryStrings = [];

const schemaUpdateQueryStrings = [
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS synced BOOLEAN DEFAULT FALSE;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS system_order_id VARCHAR(64);`,
  // 业务订单号使用 orders.order_id 字符串；老库曾误建为 BIGINT，需要保留历史值并转为字符串。
  `ALTER TABLE ${tableName} ALTER COLUMN system_order_id TYPE VARCHAR(64) USING system_order_id::VARCHAR;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS confirm_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS confirm_number VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ALTER COLUMN confirmed_at TYPE TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS room_id VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS room_name VARCHAR(255);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS source_order_id VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS hotel_id VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS contact_name VARCHAR(128);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS contact_mobile VARCHAR(128);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS number_of_guests INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS amount_before_tax DECIMAL(12, 2);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS rate_plan_id VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS biz_type INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS remark_from_douyin TEXT;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS remark_from_guest TEXT;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS daily_rates JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS occupancies JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS member_info JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS douyin_log_id VARCHAR(128);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_id VARCHAR(64);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_type INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS need_audit BOOLEAN;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS after_sale_type INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_type INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_amount DECIMAL(12, 2);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS user_refund_amount DECIMAL(12, 2);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS penalty_amount DECIMAL(12, 2);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_reason TEXT;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_order_time VARCHAR(19);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_order_detail JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_deadline VARCHAR(19);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_result INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_reason TEXT;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_response JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_sent_at TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ALTER COLUMN cancel_audit_sent_at TYPE TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_audit_retry_count INTEGER DEFAULT 0;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS fulfillment_action VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS fulfillment_response JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS fulfillment_sent_at TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ALTER COLUMN fulfillment_sent_at TYPE TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_result_response JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_result_received_at TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ALTER COLUMN refund_result_received_at TYPE TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS cancel_finish_time VARCHAR(19);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS confirm_mode INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_case_type VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_case_status VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS suggested_refund_amount DECIMAL(12, 2);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS refund_case_response JSONB;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS booking_stage VARCHAR(32);`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS booking_error_code INTEGER;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS booking_error_description TEXT;`,
  `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS booking_failure_response JSONB;`,
  // 抖音回调时间是实际发生的时间点，统一使用 TIMESTAMPTZ 交给数据库会话时区处理。
  `ALTER TABLE ${tableName} ALTER COLUMN created_at TYPE TIMESTAMPTZ;`,
  `ALTER TABLE ${tableName} ALTER COLUMN updated_at TYPE TIMESTAMPTZ;`
];

const createCommentQueryStrings = [
  `COMMENT ON TABLE ${tableName} IS '抖音OTA订单落地表';`,
  `COMMENT ON COLUMN ${tableName}.ota_order_id IS '抖音订单ID，幂等唯一键';`,
  `COMMENT ON COLUMN ${tableName}.account_id IS '抖音商家账户ID';`,
  `COMMENT ON COLUMN ${tableName}.order_status IS '抖音订单状态';`,
  `COMMENT ON COLUMN ${tableName}.guest_name IS '入住人/联系人姓名';`,
  `COMMENT ON COLUMN ${tableName}.guest_mobile IS '入住人/联系人手机号';`,
  `COMMENT ON COLUMN ${tableName}.check_in_date IS '入住日期';`,
  `COMMENT ON COLUMN ${tableName}.check_out_date IS '离店日期';`,
  `COMMENT ON COLUMN ${tableName}.room_count IS '房间数';`,
  `COMMENT ON COLUMN ${tableName}.amount IS '订单金额';`,
  `COMMENT ON COLUMN ${tableName}.currency IS '币种';`,
  `COMMENT ON COLUMN ${tableName}.raw_payload IS '抖音原始请求体';`,
  `COMMENT ON COLUMN ${tableName}.mapped_payload IS '映射后的标准字段';`,
  `COMMENT ON COLUMN ${tableName}.synced IS '是否已同步到系统订单';`,
  `COMMENT ON COLUMN ${tableName}.system_order_id IS '系统订单号(order_id)';`,
  `COMMENT ON COLUMN ${tableName}.confirm_status IS '确认状态：pending/confirmed/failed';`,
  `COMMENT ON COLUMN ${tableName}.confirm_number IS '传给抖音的确认号';`,
  `COMMENT ON COLUMN ${tableName}.confirmed_at IS '订单确认时间';`,
  `COMMENT ON COLUMN ${tableName}.room_id IS '房间ID';`,
  `COMMENT ON COLUMN ${tableName}.room_name IS '房间名称';`,
  `COMMENT ON COLUMN ${tableName}.source_order_id IS '预售来源订单号';`,
  `COMMENT ON COLUMN ${tableName}.hotel_id IS '抖音酒店ID';`,
  `COMMENT ON COLUMN ${tableName}.contact_name IS '联系人姓名';`,
  `COMMENT ON COLUMN ${tableName}.contact_mobile IS '联系人手机号/加密串';`,
  `COMMENT ON COLUMN ${tableName}.number_of_guests IS '入住人数';`,
  `COMMENT ON COLUMN ${tableName}.amount_before_tax IS '税前金额';`,
  `COMMENT ON COLUMN ${tableName}.rate_plan_id IS '抖音售卖房型ID';`,
  `COMMENT ON COLUMN ${tableName}.biz_type IS '业务类型';`,
  `COMMENT ON COLUMN ${tableName}.remark_from_douyin IS '抖音备注';`,
  `COMMENT ON COLUMN ${tableName}.remark_from_guest IS '客人备注';`,
  `COMMENT ON COLUMN ${tableName}.daily_rates IS '抖音分日价格明细';`,
  `COMMENT ON COLUMN ${tableName}.occupancies IS '入住人明细';`,
  `COMMENT ON COLUMN ${tableName}.member_info IS '会员信息';`,
  `COMMENT ON COLUMN ${tableName}.douyin_log_id IS '抖音请求头 x-bytedance-logid';`,
  `COMMENT ON COLUMN ${tableName}.cancel_id IS '取消单唯一标识';`,
  `COMMENT ON COLUMN ${tableName}.cancel_type IS '取消类型';`,
  `COMMENT ON COLUMN ${tableName}.need_audit IS '是否需要审核';`,
  `COMMENT ON COLUMN ${tableName}.after_sale_type IS '售后方式';`,
  `COMMENT ON COLUMN ${tableName}.refund_type IS '退款类型';`,
  `COMMENT ON COLUMN ${tableName}.refund_amount IS '申请退款金额';`,
  `COMMENT ON COLUMN ${tableName}.user_refund_amount IS '用户实退金额';`,
  `COMMENT ON COLUMN ${tableName}.penalty_amount IS '罚金金额';`,
  `COMMENT ON COLUMN ${tableName}.cancel_reason IS '取消原因';`,
  `COMMENT ON COLUMN ${tableName}.cancel_order_time IS '取消时间';`,
  `COMMENT ON COLUMN ${tableName}.refund_order_detail IS '售后间夜明细';`,
  `COMMENT ON COLUMN ${tableName}.cancel_status IS '取消处理状态';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_deadline IS '审核截止时间';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_result IS '审核回传结果(1同意/2拒绝)';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_reason IS '审核回传原因';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_status IS '审核回传状态';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_response IS '审核回传原始响应';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_sent_at IS '审核回传时间';`,
  `COMMENT ON COLUMN ${tableName}.cancel_audit_retry_count IS '审核回传重试次数';`,
  `COMMENT ON COLUMN ${tableName}.fulfillment_status IS '核销同步状态';`,
  `COMMENT ON COLUMN ${tableName}.fulfillment_action IS '核销同步动作';`,
  `COMMENT ON COLUMN ${tableName}.fulfillment_response IS '核销同步原始响应';`,
  `COMMENT ON COLUMN ${tableName}.fulfillment_sent_at IS '核销同步发送时间';`,
  `COMMENT ON COLUMN ${tableName}.refund_status IS '退款结果处理状态';`,
  `COMMENT ON COLUMN ${tableName}.refund_result_response IS '退款结果通知原始响应';`,
  `COMMENT ON COLUMN ${tableName}.refund_result_received_at IS '退款结果通知接收时间';`,
  `COMMENT ON COLUMN ${tableName}.cancel_finish_time IS '取消完成时间';`,
  `COMMENT ON COLUMN ${tableName}.confirm_mode IS '抖音接单模式';`,
  `COMMENT ON COLUMN ${tableName}.refund_case_type IS '退款协商类型';`,
  `COMMENT ON COLUMN ${tableName}.refund_case_status IS '退款协商状态';`,
  `COMMENT ON COLUMN ${tableName}.suggested_refund_amount IS '建议退款金额';`,
  `COMMENT ON COLUMN ${tableName}.refund_case_response IS '退款协商原始响应';`,
  `COMMENT ON COLUMN ${tableName}.booking_stage IS '创单失败阶段';`,
  `COMMENT ON COLUMN ${tableName}.booking_error_code IS '创单失败错误码';`,
  `COMMENT ON COLUMN ${tableName}.booking_error_description IS '创单失败错误描述';`,
  `COMMENT ON COLUMN ${tableName}.booking_failure_response IS '创单失败原始响应';`
];

module.exports = {
  tableName,
  createQuery,
  dropQuery,
  createIndexQueryStrings,
  schemaUpdateQueryStrings,
  createCommentQueryStrings
};
